In [1]:
from __future__ import print_function
import torch

In [2]:
import sys
print(sys.version)

3.6.4 |Anaconda, Inc.| (default, Mar 12 2018, 20:05:31) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]


## Tensors
Tensors are similar to NumPy's ndarrays, with the addition being that Tensors canalso be used on a GPU to accelerate computing.

In [8]:
# Construct 5x3 matrix, unitialized
x = torch.empty(5,3)
print(x)

tensor([[0.0000e+00, 2.0000e+00, 0.0000e+00],
        [2.0000e+00, 7.0065e-45, 0.0000e+00],
        [1.1652e-32,        nan, 1.2716e+15],
        [4.5900e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 7.0065e-45]])


In [6]:
# Construct a randomly initialized matrix
x = torch.rand(5,3)
print(x)

tensor([[0.7798, 0.7814, 0.7216],
        [0.2636, 0.4848, 0.0222],
        [0.3493, 0.9578, 0.7363],
        [0.1474, 0.1817, 0.3796],
        [0.1188, 0.9648, 0.7723]])


In [9]:
# Construct a matrix filled zeros and of dype long
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [13]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [17]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

x = torch.rand_like(x, dtype=torch.float) # override dtype
                                          # result has the same size
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.0549, 0.9255, 0.4089],
        [0.0379, 0.5886, 0.4970],
        [0.7628, 0.3962, 0.8448],
        [0.9846, 0.3227, 0.7483],
        [0.4538, 0.4694, 0.0156]])


In [18]:
print(x.size())

torch.Size([5, 3])


## Operations

In [21]:
y = torch.rand(5,3)
print(x+y)
print(torch.add(x,y))

tensor([[0.3490, 1.4814, 1.0567],
        [0.8326, 1.3831, 0.6985],
        [1.6215, 1.3388, 1.1418],
        [1.0985, 1.1950, 1.4245],
        [0.4692, 0.4717, 0.9913]])
tensor([[0.3490, 1.4814, 1.0567],
        [0.8326, 1.3831, 0.6985],
        [1.6215, 1.3388, 1.1418],
        [1.0985, 1.1950, 1.4245],
        [0.4692, 0.4717, 0.9913]])


In [22]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[0.3490, 1.4814, 1.0567],
        [0.8326, 1.3831, 0.6985],
        [1.6215, 1.3388, 1.1418],
        [1.0985, 1.1950, 1.4245],
        [0.4692, 0.4717, 0.9913]])


In [23]:
# Adds x to y
y.add_(x)
print(y)

tensor([[0.3490, 1.4814, 1.0567],
        [0.8326, 1.3831, 0.6985],
        [1.6215, 1.3388, 1.1418],
        [1.0985, 1.1950, 1.4245],
        [0.4692, 0.4717, 0.9913]])


In [24]:
print(x[:,1])

tensor([0.9255, 0.5886, 0.3962, 0.3227, 0.4694])


In [26]:
# Resizing tensor
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(), y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


## NumPy Bridge

In [32]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


a.add_(1)
print(a)
print(b) # b follows the change of a 

In [37]:
# Converting Numpy array to torch tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [39]:
# CUDA Tensors
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu",torch.double))