In [1]:
from __future__ import print_function
import torch

In [19]:
import sys
print(sys.version)
print(torch.__version__)

3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
1.0.1


## Tensors
Tensors are similar to NumPy's ndarrays, with the addition being that Tensors canalso be used on a GPU to accelerate computing.

In [3]:
# Construct 5x3 matrix, unitialized
x = torch.empty(5,3)
print(x)

tensor([[ 0.0000e+00,  8.5899e+09,  0.0000e+00],
        [ 8.5899e+09,  3.6434e-44,  0.0000e+00],
        [ 1.2757e-30,  0.0000e+00, -7.7384e+23],
        [ 4.5755e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  7.0065e-45]])


In [4]:
# Construct a randomly initialized matrix
x = torch.rand(5,3)
print(x)

tensor([[0.0707, 0.1585, 0.9385],
        [0.2181, 0.5402, 0.7016],
        [0.8760, 0.4098, 0.5432],
        [0.2294, 0.5457, 0.0197],
        [0.5658, 0.9815, 0.1583]])


In [5]:
# Construct a matrix filled zeros and of dype long
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

x = torch.rand_like(x, dtype=torch.float) # override dtype
                                          # result has the same size
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.4902, 0.6233, 0.4469],
        [0.5859, 0.0603, 0.8070],
        [0.1850, 0.2655, 0.1542],
        [0.6545, 0.6436, 0.1836],
        [0.8829, 0.3339, 0.1944]])


In [8]:
print(x.size())

torch.Size([5, 3])


## Operations

In [9]:
y = torch.rand(5,3)
print(x+y)
print(torch.add(x,y))

tensor([[0.7267, 1.5144, 0.5928],
        [1.5856, 0.1185, 1.1273],
        [0.3429, 0.9957, 0.6141],
        [1.4339, 1.4582, 0.4323],
        [1.3163, 0.5069, 0.8610]])
tensor([[0.7267, 1.5144, 0.5928],
        [1.5856, 0.1185, 1.1273],
        [0.3429, 0.9957, 0.6141],
        [1.4339, 1.4582, 0.4323],
        [1.3163, 0.5069, 0.8610]])


In [10]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[0.7267, 1.5144, 0.5928],
        [1.5856, 0.1185, 1.1273],
        [0.3429, 0.9957, 0.6141],
        [1.4339, 1.4582, 0.4323],
        [1.3163, 0.5069, 0.8610]])


In [11]:
# Adds x to y
y.add_(x)
print(y)

tensor([[0.7267, 1.5144, 0.5928],
        [1.5856, 0.1185, 1.1273],
        [0.3429, 0.9957, 0.6141],
        [1.4339, 1.4582, 0.4323],
        [1.3163, 0.5069, 0.8610]])


In [12]:
print(x[:,1])

tensor([0.6233, 0.0603, 0.2655, 0.6436, 0.3339])


In [13]:
# Resizing tensor
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(), y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


## NumPy Bridge

In [14]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


a.add_(1)
print(a)
print(b) # b follows the change of a 

In [15]:
# Converting Numpy array to torch tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [16]:
# CUDA Tensors
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu",torch.double))

## AUTOGRAD: Automatic Differentiation

x = torch.ones(2, 2, requires_grad=True)
print(x)

In [22]:
y = x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [23]:
print(y.grad_fn)

In [24]:
z = y*y*3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [28]:
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


## Gradient

In [ ]:
out.backward()

In [32]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [33]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-785.6834, -339.9073,  999.8305], grad_fn=<MulBackward0>)


In [34]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [35]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
